language: node_js
node_js:
- 4.2.3
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
before_deploy:
- grunt build
- ls -ltra
deploy:
  app: solnet-leads-dev
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: D9FGHpcxZAZ19IrFvv97Ts2H3bJWDwa8AGWogylR36d8QDanPzzGqiyXnL7Wgo7/kXyJtStI1gt6lt6di4UYbmXSvYywgUr4gY07+UENJRVWEOHLkDJMjyfSe/9Sj8iQMz6pcnCo7FYB/XYKzWnuIIHy1uj5VpU75v/SSdwSxkpd0ETdvHGKv3gsk/LPf53qxAYwx0XKNSVKiCRHuVpdQqkTAndKmvlViNTGWs+huRXnmuiJKKVWKUKyMuSkjxRkPe3aCQ1+T8zAarqkahBhR8LAmrDQUcaQEOVxLoMqkNU0hNDWSntpiXYiZeMHo3dNLZFBMYaBIs5HJK0P2NlQNQdBzc5gBsXSE2tZH/Fmv6KBc5OjTiHL2IXdO9fMxAut1Xw7c6cIr+unRVfvrlhJ9baY9Ny4caQpboU9NyX5TPA+kQ/T6+3Zly0JJpZ/flCcxwAcWwyjmGqZ6CYiVuN6gEMZwZVA4/CBRXUDv2usuV2XOBSP3vDyIbHi/2t5xdIHSB7lGTsbouVUi31l0nfriIFSsfKQ2dG3SqiFxhnkmpOmq6I80vbP5RobvSZ+ueEeNo2mx35yDBuN2ltdvSsfRP3KA2Ex6FiLlnylWhpN9k1aIuxGldGyOWPSF5eta6MOs5nixD7b3ZkIsSXvgRvOjTGNlmt5yyAtrpAQAnm7Gkc=
cache:
  directories:
  - node_modules
